# Generated by Django 3.0.3 on 2020-04-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
