# Generated by Django 3.0.3 on 2020-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
