# Generated by Django 3.0.3 on 2020-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200407_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(default='/static/images/campus.jpg', upload_to='media/pics'),
        ),
    ]
