# Generated by Django 3.0.3 on 2020-04-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200408_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'UserInfos'},
        ),
    ]
