# Generated by Django 3.0.3 on 2020-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200408_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile_pics/def.jpg', upload_to='profile_pics'),
        ),
    ]
