# Generated by Django 3.0.3 on 2020-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200408_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(default='/pics/campus.jpg', upload_to='pics'),
        ),
    ]
