# Generated by Django 3.0.3 on 2020-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200419_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
