# Generated by Django 3.0.3 on 2020-04-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_posts_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_liked',
        ),
    ]
