# Generated by Django 3.0.3 on 2020-04-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_posts_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_bio',
            field=models.TextField(blank=True),
        ),
    ]
