# Generated by Django 3.0.3 on 2020-05-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200425_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/static/images/def.png', upload_to='profile_pics'),
        ),
    ]
