# Generated by Django 3.0.3 on 2020-05-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200502_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_hot',
        ),
    ]
