# Generated by Django 3.0.3 on 2020-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_posts_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_static',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
